version: "3.9"

################################################################################
# DEFAULT CONF https://stackoverflow.com/a/65522511

x-healthcheck_conf: &healthcheck_conf
      interval: 5s
      retries: 30

x-restart: &restart
    restart: on-failure

################################################################################

services:
  ##############################################################################
  # Nginx (reverse proxy)
  nginx:
    container_name: nginx
    build:
      context: "./build/nginx"
      target: packed
    depends_on:
      angularjs:
        condition: service_completed_successfully
      nestjs:
        condition: service_healthy
    environment:
      - CERT_SUBJ=${CERT_SUBJ?}
      - DOCKER_DEBUG=${DOCKER_DEBUG?}
    ports:
      - 127.0.0.1:${NGINX_PORT?}:443
    networks:
      transendence:
        ipv4_address: "13.37.42.10"
    volumes:
      - type: bind
        source: ./volume/log/nginx
        target: /var/log/nginx
        bind:
          create_host_path: true
      - type: bind
        source: ./volume/angularjs
        target: /app
        bind:
          create_host_path: true
      - type: bind
        source: ./volume/nginx
        target: /etc/nginx
        bind:
          create_host_path: true
    << : *restart
    healthcheck:
      test: "nc -w ${DOCKER_TIMEOUT?} 127.0.0.1 443"
      << : *healthcheck_conf
  #
  ##############################################################################

  ##############################################################################
  # NestJS
  nestjs:
    container_name: nestjs
    hostname: nestjs
    build:
      context: "./build/nodejs"
      target: "nodejs"
    depends_on:
      postgresql:
        condition: service_healthy
    command: [ "npm", "run", "prod" ]
    networks:
      transendence:
        ipv4_address: "13.37.42.11"
    environment:
      - DB_USER=${ADMIN_USER?}
      - DB_PASS=${ADMIN_PASS?}
      - DB_NAME=${DB_NAME?}
      - API42_USERID=${API42_USERID?}
      - API42_SECRET=${API42_SECRET?}
      - API42_REDIRECTURL=${API42_REDIRECTURL_PROD?}
      - JWT_SECRET=${JWT_SECRET?}
      - PRODUCTION=1
    volumes:
      - type: bind
        source: ./volume/nodejs
        target: /usr/local/lib/nodejs
        bind:
          create_host_path: true
      - type: bind
        source: ./src/nestjs
        target: /shared/transcendence
        bind:
          create_host_path: true
    << : *restart
    healthcheck:
      test: "nc -w ${DOCKER_TIMEOUT?} 127.0.0.1 3000"
      << : *healthcheck_conf
  #
  ##############################################################################

  ##############################################################################
  # AngularJS
  angularjs:
    container_name: angularjs
    hostname: angularjs
    build:
      context: "./build/nodejs"
      target: "nodejs"
    command: [ "npm", "run", "prod" ]
    networks:
      transendence:
        ipv4_address: "13.37.42.12"
    volumes:
      - type: bind
        source: ./volume/nodejs
        target: /usr/local/lib/nodejs
        bind:
          create_host_path: true
      - type: bind
        source: ./src/angularjs
        target: /shared/transcendence
        bind:
          create_host_path: true
      - type: bind
        source: ./volume/angularjs
        target: /build/
        bind:
          create_host_path: true
    << : *restart
  #
  ##############################################################################

  ##############################################################################
  # PostgreSQL
  postgresql:
    container_name: postgresql
    build:
      context: "./build/postgresql"
      target: "packed"
    environment:
      - ADMIN_USER=${ADMIN_USER?}
      - ADMIN_PASS=${ADMIN_PASS?}
      - DB_NAME=${DB_NAME?}
      - PGDATA=/usr/local/pgsql/data
      - DOCKER_DEBUG=${DOCKER_DEBUG?}
    networks:
      transendence:
        ipv4_address: "13.37.42.13"
    volumes:
      - type: bind
        source: ./volume/postgresql
        target: /usr/local/pgsql/data
        bind:
          create_host_path: true
      - type: bind
        source: ./volume/log/postgresql
        target: /var/log/postgresql
        bind:
          create_host_path: true
    << : *restart
    healthcheck:
      test: "nc -w ${DOCKER_TIMEOUT?} 127.0.0.1 5432"
      << : *healthcheck_conf
  #
  ##############################################################################

networks:
  ##############################################################################
  # MAIN INTERNAL NETWORK (netpractice)
  transendence:
    name: transendence
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: transendence
    ipam:
      driver: default
      config:
        - subnet: 13.37.42.0/27
          ip_range: 13.37.42.0/27
          gateway: 13.37.42.1
  #
  ##############################################################################
