version: "3.9"

################################################################################
# DEFAULT CONF https://stackoverflow.com/a/65522511

x-healthcheck_conf: &healthcheck_conf
      interval: 1s
      timeout: 1s
      retries: 50

x-restart: &restart
    restart: on-failure

################################################################################

services:
  ##############################################################################
  # NodeJS
  nodejs:
    container_name: nodejs
    build:
      context: "./docker/nodejs"
      target: "packed"
      args:
        - PROJECT_NAME=${PROJECT_NAME}
    environment:
      - PROJECT_NAME=${PROJECT_NAME}
    ports:
      - 3000:3000
    networks:
      transendence:
        ipv4_address: "13.37.42.11"
    volumes:
      - nodejs:/usr/local/lib/nodejs
      - node_src:/shared/${PROJECT_NAME}
    << : *restart
    # healthcheck:
    #   test: [ "CMD", "pgrep", "node" ]
    #   << : *healthcheck_conf
  #
  ##############################################################################

  ##############################################################################
  # PostgreSQL
  postgresql:
    container_name: postgresql
    build:
      context: "./docker/postgresql"
      target: "packed"
    environment:
      - ADMIN_USER=${ADMIN_USER}
      - ADMIN_PASS=${ADMIN_PASS}
      - DB_NAME=${DB_NAME}
      - PGDATA=/usr/local/pgsql/data
      - DEBUG=${DEBUG}
    networks:
      transendence:
        ipv4_address: "13.37.42.12"
    volumes:
      - postgresql:/usr/local/pgsql/data
      - postgresql_log:/var/log/postgresql
    << : *restart
    healthcheck:
      test: [ "CMD", "pgrep", "postgres" ]
      << : *healthcheck_conf
  #
  ##############################################################################

  ##############################################################################
  # Portainer
  portainer:
    container_name: portainer
    build:
      context: "./docker/portainer"
      target: "packed"
    environment:
      - CERT_SUBJ=${CERT_SUBJ}
      - ADMIN_PASS=${ADMIN_PASS}
      - DEBUG=${DEBUG}
    ports:
      - 9443:9443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer:/data
    networks:
      transendence:
        ipv4_address: "13.37.42.10"
    << : *restart
    healthcheck:
      test: [ "CMD", "pgrep", "portainer" ]
      << : *healthcheck_conf
  #
  ##############################################################################

networks:
  ##############################################################################
  # MAIN INTERNAL NETWORK (netpractice)
  transendence:
    name: transendence
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: transendence
    ipam:
      driver: default
      config:
        - subnet: 13.37.42.0/27
          ip_range: 13.37.42.0/27
          gateway: 13.37.42.1
  #
  ##############################################################################

volumes:

  ##############################################################################
  # NodeJS install dir
  nodejs:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: ../shared/nodejs
  #
  ##############################################################################

  ##############################################################################
  # NodeJS Shared src
  node_src:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: ./nodejs/src/${PROJECT_NAME}
  #
  ##############################################################################

  ##############################################################################
  # PostgreSQL
  postgresql:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: ../shared/postgresql

  # PostgreSQL Log
  postgresql_log:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: ../shared/postgresql_log
  #
  ##############################################################################

  ##############################################################################
  # Portainer
  portainer:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: ../shared/portainer
  #
  ##############################################################################
