version: "3.9"

################################################################################
# DEFAULT CONF https://stackoverflow.com/a/65522511

x-healthcheck_conf: &healthcheck_conf
      interval: 1s
      timeout: 1s
      retries: 50

x-restart: &restart
    restart: on-failure

################################################################################

services:
  ##############################################################################
  # NodeJS
  nodejs:
    container_name: nodejs
    build:
      context: "./docker/nodejs"
      target: "packed"
    networks:
      transendence:
        ipv4_address: "13.37.42.11"
    volumes:
      - nodejs:/usr/local/lib/nodejs
    << : *restart
    # healthcheck:
    #   test: [ "CMD", "pgrep", "node" ]
    #   << : *healthcheck_conf
  #
  ##############################################################################

  ##############################################################################
  # PostgreSQL
  postgres:
    container_name: postgres
    build:
      context: "./docker/postgres"
      target: "packed"
    # volumes:
    #   - postgres:/usr/local/pgsql/data
    environment:
      - ADMIN_USER=${ADMIN_USER}
      - ADMIN_PASS=${ADMIN_PASS}
      - DB_NAME=${DB_NAME}
      - PGDATA=/usr/local/pgsql/data
      - DEBUG=${DEBUG}
    networks:
      transendence:
        ipv4_address: "13.37.42.12"
    << : *restart
    healthcheck:
      test: [ "CMD", "pgrep", "postgres" ]
      << : *healthcheck_conf
  #
  ##############################################################################

  ##############################################################################
  # Portainer
  portainer:
    container_name: portainer
    build:
      context: "./docker/portainer"
      target: "packed"
    environment:
      - CERT_SUBJ=${CERT_SUBJ}
      - ADMIN_PASS=${ADMIN_PASS}
      - DEBUG=${DEBUG}
    ports:
      - 9443:9443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer:/data
    networks:
      transendence:
        ipv4_address: "13.37.42.10"
    << : *restart
    healthcheck:
      test: [ "CMD", "pgrep", "portainer" ]
      << : *healthcheck_conf
  #
  ##############################################################################

networks:
  ##############################################################################
  # MAIN INTERNAL NETWORK (netpractice)
  transendence:
    name: transendence
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: transendence
    ipam:
      driver: default
      config:
        - subnet: 13.37.42.0/27
          ip_range: 13.37.42.0/27
          gateway: 13.37.42.1
  #
  ##############################################################################

volumes:

  ##############################################################################
  # SOME LOGS
  nodejs:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: ../shared/nodejs
  #
  ##############################################################################

  # ##############################################################################
  # # PostgreSQL
  # postgres:
  #   driver: local
  #   driver_opts:
  #     type: "none"
  #     o: "bind"
  #     device: ../shared/postgres
  # #
  # ##############################################################################

  ##############################################################################
  # Portainer
  portainer:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: ../shared/portainer
  #
  ##############################################################################
