version: "3.9"

################################################################################
# DEFAULT CONF https://stackoverflow.com/a/65522511

x-healthcheck_conf: &healthcheck_conf
      interval: 1s
      timeout: 1s
      retries: 50

x-restart: &restart
    restart: on-failure

################################################################################

services:
  ##############################################################################
  # NodeJS
  nodejs:
    container_name: nodejs
    build:
      context: "./docker/nodejs"
      target: "packed"
    networks:
      inception_net:
        ipv4_address: "13.37.42.11"
    volumes:
      - node:/Shared
    << : *restart
    # healthcheck:
    #   test: [ "CMD", "pgrep", "node" ]
    #   << : *healthcheck_conf
  #
  ##############################################################################

  ##############################################################################
  # Portainer
  portainer:
    container_name: portainer
    build:
      context: "./docker/portainer"
      target: "packed"
    environment:
      - CERT_SUBJ=${CERT_SUBJ}
      - ADMIN_PASS=${ADMIN_PASS}
      - DEBUG=${DEBUG:-}
    ports:
      - 9443:9443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      inception_net:
        ipv4_address: "13.37.42.10"
    << : *restart
    healthcheck:
      test: [ "CMD", "pgrep", "portainer" ]
      << : *healthcheck_conf
  #
  ##############################################################################

networks:
  ##############################################################################
  # MAIN INTERNAL NETWORK (netpractice)
  inception_net:
    name: transendence
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: transendence
    ipam:
      driver: default
      config:
        - subnet: 13.37.42.0/27
          ip_range: 13.37.42.0/27
          gateway: 13.37.42.1
  #
  ##############################################################################

volumes:

  ##############################################################################
  # SOME LOGS
  node:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: ./Shared/node
  #
  ##############################################################################

  ##############################################################################
  # Portainer
  portainer_data:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: ./Shared/portainer
  #
  ##############################################################################
