#!/bin/ash

SERVICE_NAME="NodeJS"

if [ "${DEBUG}" != "" ]; then
	printf "debuging \x1b[38:5:39m${SERVICE_NAME}\x1b[00m \n\n"
	printf "DEBUG     %s\n\n" "${DEBUG}"
fi

function	update_nodejs()
{
	npm update -g && npm upgrade -g
	# npx --yes npm-check --global --update-all
}

function	install_nestjs()
{
	npm i -g @nestjs/cli
	init_project_nestjs
}

function	install_angularjs()
{
	npm i -g @angular/cli
}

function	init_project_nestjs()
{
	cd "/shared/${PROJECT_NAME}"
	if [ ! -d "/shared/${PROJECT_NAME}/src" ]; then
		nest new --package-manager npm --directory . ${PROJECT_NAME}
	fi
	npm install
}

if [ ! -d "/shared/${PROJECT_NAME}/node_modules" ]; then
	update_nodejs
	[ "$(hostname)" == "nestjs" ] && install_nestjs || install_angularjs
fi

printf "${SERVICE_NAME} launched\n"

exec ${@}
