#!/bin/ash

SERVICE_NAME="NodeJS"
NODE_OPT="--package-manager npm --directory . --skip-git"

if [ "${DEBUG}" != "" ]; then
	printf "debuging \x1b[38:5:39m${SERVICE_NAME}\x1b[00m \n\n"
	printf "DEBUG     %s\n\n" "${DEBUG}"
fi

function	update_nodejs()
{
	npm update -g && npm upgrade -g
	# npx --yes npm-check --global --update-all
}

function	init_project_nestjs()
{
	cd "/shared/${PROJECT_NAME}"
	if [ ! -d "/shared/${PROJECT_NAME}/src" ]; then
		nest new ${NODE_OPT} "${PROJECT_NAME}"
	fi
	npm install
}

function	init_project_angularjs()
{
	cd "/shared/${PROJECT_NAME}"
	if [ ! -d "/shared/${PROJECT_NAME}/src" ]; then
		ng new ${NODE_OPT} --routing false --style scss "${PROJECT_NAME}"
	fi
	sed -i "s/^    \"start\":.*/    \"start\":\"ng serve --host 0.0.0.0\",/g" package.json
	npm install
}

function	install_nestjs()
{
	npm i -g @nestjs/cli
	init_project_nestjs
}

function	install_angularjs()
{
	npm i -g @angular/cli
	init_project_angularjs
}

if [ ! -d "/shared/${PROJECT_NAME}/node_modules" ]; then
	update_nodejs
	[ "$(hostname)" == "nestjs" ] && install_nestjs || install_angularjs
fi

chmod -R 777 "/shared/${PROJECT_NAME}"

printf "${SERVICE_NAME} launched\n"

exec ${@}
