#!/bin/bash

TOK=$(cat .tok)

function do4time()
{
	local path="${1}"

	for i in {1..4}
	do
		TOKEN=$TOK .././postman ${path}$i
	done
}

# test post/create function
#do4time "fill_db/post/user/user"
#do4time "fill_db/post/chatRoom/room"
do4time "fill_db/post/userChatRoom/user1inroom"
# do4time "fill_db/post/gameInfo/gameInfo"
# do4time "fill_db/post/message/db/user1ToRoom"

# test put/update function
# do4time "fill_db/put/db/user/db/user"
# do4time "fill_db/put/db/chat_room/room"
# do4time "fill_db/put/db/user_chat_room/db/db/user_chat_room"
# do4time "fill_db/put/message/message"
# do4time "fill_db/put/gameInfo/gameInfo"
