name: CD

run-name: CD Deployment to my home

on:
  push:
    branches: [main]

jobs:
  deploy-to-pix-home:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: 🔧 Install SSH keys
        run: |+
          rm -f ~/.ssh && mkdir ~/.ssh
          echo "${{ secrets.HOME_SSH_KEY }}" > ~/.ssh/id_rsa.pem
          ssh-keyscan -p ${{ secrets.HOME_SSH_PORT }} -H ${{ secrets.HOME_IP }} > ~/.ssh/known_hosts
          chmod 700 ~/.ssh/
          chmod 600 ~/.ssh/*

      - name: 🤖 Connect to HOME
        run: |+
          ssh ${{ secrets.HOME_SSH_USER }}@${{ secrets.HOME_IP }} -i ~/.ssh/id_rsa.pem -p ${{ secrets.HOME_SSH_PORT }} <<-EOFDEPLOY
            cd Documents/ft_transcendence
            docker compose down
            GIT_SSH_COMMAND="ssh -i /home/pix/.ssh/git" git pull
            docker compose up --build -d --wait
          EOFDEPLOY

      - name: 🧹 Cleaning up SSH key
        run: rm -rf ./.ssh
