name: CD

run-name: Deployment

on:
  push:
    branches: [main]

jobs:
  deploy-to-host:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: 🔧 Install SSH keys
        run: |+
          rm -f ~/.ssh && mkdir ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa.pem
          ssh-keyscan -p ${{ secrets.SSH_PORT }} -H ${{ secrets.HOST_IP }} > ~/.ssh/known_hosts
          chmod 700 ~/.ssh/
          chmod 600 ~/.ssh/*

      - name: 🤖 Connect to HOME
        run: |+
          ssh ${{ secrets.SSH_USER }}@${{ secrets.HOST_IP }} -i ~/.ssh/id_rsa.pem -p ${{ secrets.SSH_PORT }} <<-EOFDEPLOY
            cd Documents/ft_transcendence
            docker compose down
            git reset --hard HEAD && git pull
            printf "${{ secrets.SETUP_STR }}\n" | SOCKET_URL="https://${{ secrets.HOST_IP }}" ./setup deploy
            docker compose up --build -d --wait
          EOFDEPLOY

      - name: 🧹 Cleaning up SSH key
        run: rm -rf ./.ssh
