name: Docker compose check

run-name: Docker compose CI

on:
  push:

jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - name: "github"
        run: |+
          echo "Who launched: ${{github.actor}}"
          echo "On branch:    ${{github.ref_name}}"
          echo "Commit sha:   ${{github.sha}}"

  docker-build-prod:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .env
        run: printf "pix\n1234\n1234\n1234\n1234" | ./setup
      - name: Build prod
        run: docker compose build --no-cache

  docker-run-prod:
    needs: docker-build-prod
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .env
        run: printf "pix\n1234\n1234\n1234\n1234" | ./setup
      - name: Executing debug
        run: docker compose up --build -d --wait

  docker-build-dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .env
        run: printf "pix\n1234\n1234\n1234\n1234" | ./setup
      - name: Switching to debug
        run: sed -i "s|DEBUG=|DEBUG=1|g" .env
      - name: Build debug
        run: docker compose build --no-cache

  docker-run-dev:
    needs: docker-build-dev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .env
        run: printf "pix\n1234\n1234\n1234\n1234" | ./setup
      - name: Switching to debug
        run: sed -i "s|DEBUG=|DEBUG=1|g" .env
      - name: Executing debug
        run: docker compose up --build -d --wait
