name: Docker compose check

run-name: Docker compose CI

on:
  push:
    branches: [main]

jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - name: "github"
        run: |+
          echo "Who launched: ${{github.actor}}"
          echo "On branch:    ${{github.ref_name}}"
          echo "Commit sha:   ${{github.sha}}"

  docker-prod-build:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .env
        run: printf "pix\n1234\n1234\n1234\n1234" | ./setup
      - name: Build prod
        run: docker compose build --no-cache

  docker-prod-run:
    timeout-minutes: 10
    needs: docker-prod-build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .env
        run: printf "pix\n1234\n1234\n1234\n1234" | ./setup
      - name: Executing prod
        run: docker compose up --build -d --wait

  docker-dev-build:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .env
        run: printf "pix\n1234\n1234\n1234\n1234" | ./setup
      - name: Switching to debug
        run: sed -i "s|DEBUG=|DEBUG=1|g" .env
      - name: Build debug
        run: docker compose build --no-cache

  docker-dev-run:
    timeout-minutes: 10
    needs: docker-dev-build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .env
        run: printf "pix\n1234\n1234\n1234\n1234" | ./setup
      - name: Switching to debug
        run: sed -i "s|DEBUG=|DEBUG=1|g" .env
      - name: Executing debug
        run: docker compose up --build -d --wait
