name: Docker compose check

run-name: Docker compose CI

env:
  ACTOR: ${{ github.actor }}

on:
  push:

jobs:
  startup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
        printf "%s triggered the actions\n" "${ACTOR}"
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - run: printf "pix\n1234\n1234\n1234\n1234" | ./setup
      - run: cp .env{.template,}
      - run: docker compose build --no-cache
      - run: sed -i "s|DEBUG=|DEBUG=1|g" .env
      - run: docker compose build --no-cache
