name: CI

run-name: CI for ft_transcendence

on:
  pull_request:

jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - name: 💬 github
        run: |+
          echo "Who launched: ${{ github.actor }}"
          echo "On branch:    ${{ github.ref_name }}"
          echo "Commit sha:   ${{ github.sha }}"
          echo "Vars"
          echo "SETUP_STR ${{ vars.SETUP_STR }}"

      - name: 💬 docker | compose
        run: |+
          docker version
          docker compose version

  do-docker-prod:
    uses: ./.github/workflows/CI-docker.yaml
    with:
      mode: prod

  do-docker-dev:
    uses: ./.github/workflows/CI-docker.yaml
    with:
      mode: dev

  do-nest-prod:
    needs: do-docker-prod
    uses: ./.github/workflows/CI-nest.yaml
    with:
      mode: prod

  do-nest-dev:
    needs: do-docker-dev
    uses: ./.github/workflows/CI-nest.yaml
    with:
      mode: dev
