name: Docker compose check

run-name: Docker compose CI

on:
  push:

jobs:
  docker-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: printf "pix\n1234\n1234\n1234\n1234" | ./setup
      - run: cp .env{.template,}
      - run: docker build
      - run: sed -i "s|DEBUG=|DEBUG=1|g" .env
      - run: docker build
