name: Docker compose check

run-name: Docker compose CI

on:
  push:

jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - name: "github"
        run: |+
          echo "Who launched: ${{github.actor}}"
          echo "On branch:    ${{github.ref_name}}"
          echo "Commit sha:   ${{github.sha}}"

  docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup .env
        run: |+
          printf "pix\n1234\n1234\n1234\n1234" | ./setup
          cp .env{.template,}

      - name: Build prod
        run: docker compose build --no-cache

      - name: Switching to debug
        run: sed -i "s|DEBUG=|DEBUG=1|g" .env

      - name: Build debug
        run: docker compose build --no-cache

  docker-run:
    needs: docker-build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup .env
        run: |+
          printf "pix\n1234\n1234\n1234\n1234" | ./setup
          cp .env{.template,}

      - name: Executing prod
        run: docker compose up --wait

      - name: Switching to debug
        run: sed -i "s|DEBUG=|DEBUG=1|g" .env

      - name: Executing debug
        run: docker compose up --wait
